export type VisaType =
  | 'visa-free'
  | 'visa-on-arrival'
  | 'e-visa'
  | 'schengen'
  | 'check-required'
  | 'visa-required'

export type Region = 'Europe' | 'Asia' | 'Middle East' | 'Africa' | 'Americas' | 'Oceania'
export type TravelStyle = 'budget' | 'mid' | 'luxury'
export type Tag = 'beach' | 'city' | 'culture' | 'nature' | 'adventure' | 'food' | 'history' | 'nightlife' | 'romance' | 'family'

export interface Destination {
  slug: string
  city: string
  country: string
  region: Region
  flag: string
  coverEmoji: string
  description: string
  tags: Tag[]
  avgDailyEur: number
  travelStyle: TravelStyle
  bestMonths: number[]
  visaForIndianPassport: VisaType
  visaForEuPassport: VisaType
  visaNote?: string
  flightHoursFromEurope: number
  highlights: string[]
}

export const DESTINATIONS: Destination[] = [

  // ── EUROPE ─────────────────────────────────────────────────────────────────

  {
    slug: 'paris',
    city: 'Paris', country: 'France', region: 'Europe', flag: '🇫🇷', coverEmoji: '🗼',
    description: 'The city of light — art, fashion, food and iconic landmarks.',
    tags: ['city', 'culture', 'food', 'history', 'romance'],
    avgDailyEur: 120, travelStyle: 'mid', bestMonths: [4, 5, 6, 9, 10],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 1,
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Montmartre & Seine cruises'],
  },
  {
    slug: 'rome',
    city: 'Rome', country: 'Italy', region: 'Europe', flag: '🇮🇹', coverEmoji: '🏛️',
    description: 'Eternal city of ancient ruins, Renaissance art and world-class pasta.',
    tags: ['city', 'culture', 'history', 'food'],
    avgDailyEur: 100, travelStyle: 'mid', bestMonths: [3, 4, 5, 9, 10, 11],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Colosseum', 'Vatican City', 'Trevi Fountain'],
  },
  {
    slug: 'barcelona',
    city: 'Barcelona', country: 'Spain', region: 'Europe', flag: '🇪🇸', coverEmoji: '🎨',
    description: 'Gaudí architecture, beaches and legendary nightlife all in one city.',
    tags: ['city', 'beach', 'culture', 'nightlife', 'food'],
    avgDailyEur: 110, travelStyle: 'mid', bestMonths: [4, 5, 6, 9, 10],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Sagrada Família', 'Park Güell', 'La Barceloneta beach'],
  },
  {
    slug: 'amsterdam',
    city: 'Amsterdam', country: 'Netherlands', region: 'Europe', flag: '🇳🇱', coverEmoji: '🚲',
    description: 'Canals, world-class museums and a famously free-spirited culture.',
    tags: ['city', 'culture', 'history'],
    avgDailyEur: 130, travelStyle: 'mid', bestMonths: [4, 5, 6, 7, 8, 9],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 1,
    highlights: ['Rijksmuseum', 'Anne Frank House', 'Canal ring cruises'],
  },
  {
    slug: 'prague',
    city: 'Prague', country: 'Czech Republic', region: 'Europe', flag: '🇨🇿', coverEmoji: '🏰',
    description: 'A fairy-tale medieval city with stunning architecture and cheap beer.',
    tags: ['city', 'culture', 'history', 'nightlife'],
    avgDailyEur: 65, travelStyle: 'budget', bestMonths: [3, 4, 5, 9, 10, 11],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 1,
    highlights: ['Old Town Square', 'Prague Castle', 'Charles Bridge'],
  },
  {
    slug: 'vienna',
    city: 'Vienna', country: 'Austria', region: 'Europe', flag: '🇦🇹', coverEmoji: '🎻',
    description: 'Imperial palaces, Mozart, coffee house culture and the Vienna Philharmonic.',
    tags: ['city', 'culture', 'history', 'food'],
    avgDailyEur: 115, travelStyle: 'mid', bestMonths: [3, 4, 5, 9, 10],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Schönbrunn Palace', 'Belvedere', 'Vienna State Opera'],
  },
  {
    slug: 'lisbon',
    city: 'Lisbon', country: 'Portugal', region: 'Europe', flag: '🇵🇹', coverEmoji: '🛤️',
    description: 'Trams, Fado music, pastéis de nata and the best sunset in Europe.',
    tags: ['city', 'culture', 'food', 'history'],
    avgDailyEur: 85, travelStyle: 'mid', bestMonths: [3, 4, 5, 9, 10, 11],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Alfama district', 'Belém Tower', 'Sintra day trip'],
  },
  {
    slug: 'athens',
    city: 'Athens', country: 'Greece', region: 'Europe', flag: '🇬🇷', coverEmoji: '🏺',
    description: 'The cradle of Western civilisation with iconic ruins and great seafood.',
    tags: ['city', 'culture', 'history', 'food'],
    avgDailyEur: 80, travelStyle: 'mid', bestMonths: [3, 4, 5, 9, 10, 11],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 3,
    highlights: ['Acropolis & Parthenon', 'Plaka neighbourhood', 'National Archaeology Museum'],
  },
  {
    slug: 'berlin',
    city: 'Berlin', country: 'Germany', region: 'Europe', flag: '🇩🇪', coverEmoji: '🐻',
    description: 'Edgy, creative and historically fascinating — Europe\'s coolest capital.',
    tags: ['city', 'culture', 'history', 'nightlife'],
    avgDailyEur: 95, travelStyle: 'mid', bestMonths: [4, 5, 6, 7, 8, 9],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 1,
    highlights: ['Brandenburg Gate', 'Berlin Wall Memorial', 'Museum Island'],
  },
  {
    slug: 'budapest',
    city: 'Budapest', country: 'Hungary', region: 'Europe', flag: '🇭🇺', coverEmoji: '🌉',
    description: 'Grand thermal baths, ruin bars and a stunning Danube skyline.',
    tags: ['city', 'culture', 'history', 'nightlife'],
    avgDailyEur: 60, travelStyle: 'budget', bestMonths: [3, 4, 5, 9, 10],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Parliament Building', 'Széchenyi Baths', 'Ruin bar district'],
  },
  {
    slug: 'dubrovnik',
    city: 'Dubrovnik', country: 'Croatia', region: 'Europe', flag: '🇭🇷', coverEmoji: '🏖️',
    description: 'The Pearl of the Adriatic — Game of Thrones filming location.',
    tags: ['beach', 'culture', 'history', 'romance'],
    avgDailyEur: 110, travelStyle: 'mid', bestMonths: [5, 6, 9, 10],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Old City walls walk', 'Lokrum Island', 'Cable car views'],
  },
  {
    slug: 'santorini',
    city: 'Santorini', country: 'Greece', region: 'Europe', flag: '🇬🇷', coverEmoji: '🌅',
    description: 'Blue-domed churches, white-washed cliffs and breathtaking caldera sunsets.',
    tags: ['beach', 'romance', 'culture'],
    avgDailyEur: 180, travelStyle: 'luxury', bestMonths: [4, 5, 6, 9, 10],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 3,
    highlights: ['Oia sunset', 'Caldera boat tour', 'Red & Black Beach'],
  },
  {
    slug: 'porto',
    city: 'Porto', country: 'Portugal', region: 'Europe', flag: '🇵🇹', coverEmoji: '🍷',
    description: 'Port wine, colourful azulejo tiles and riverside charm.',
    tags: ['city', 'culture', 'food'],
    avgDailyEur: 75, travelStyle: 'budget', bestMonths: [4, 5, 6, 9, 10],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Ribeira waterfront', 'Port wine cellars', 'São Bento station tiles'],
  },
  {
    slug: 'stockholm',
    city: 'Stockholm', country: 'Sweden', region: 'Europe', flag: '🇸🇪', coverEmoji: '⚓',
    description: 'Scandinavia\'s most beautiful city — on 14 islands with world-class design.',
    tags: ['city', 'culture', 'nature'],
    avgDailyEur: 145, travelStyle: 'mid', bestMonths: [5, 6, 7, 8],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Gamla Stan', 'Vasa Museum', 'ABBA Museum'],
  },
  {
    slug: 'reykjavik',
    city: 'Reykjavik', country: 'Iceland', region: 'Europe', flag: '🇮🇸', coverEmoji: '🌋',
    description: 'Northern lights, geysers, waterfalls and the midnight sun.',
    tags: ['nature', 'adventure', 'culture'],
    avgDailyEur: 200, travelStyle: 'mid', bestMonths: [3, 4, 6, 7, 8, 9],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 3,
    highlights: ['Northern Lights', 'Golden Circle', 'Blue Lagoon'],
  },
  {
    slug: 'krakow',
    city: 'Kraków', country: 'Poland', region: 'Europe', flag: '🇵🇱', coverEmoji: '🏰',
    description: 'Medieval splendour, Jewish heritage and the best budget city in Europe.',
    tags: ['city', 'culture', 'history'],
    avgDailyEur: 50, travelStyle: 'budget', bestMonths: [4, 5, 6, 9, 10],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Wawel Castle', 'Auschwitz memorial', 'Kazimierz district'],
  },
  {
    slug: 'edinburgh',
    city: 'Edinburgh', country: 'United Kingdom', region: 'Europe', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', coverEmoji: '🏰',
    description: 'A dramatic castle on volcanic rock, whisky and the world\'s best arts festival.',
    tags: ['city', 'culture', 'history'],
    avgDailyEur: 110, travelStyle: 'mid', bestMonths: [5, 6, 7, 8, 9],
    visaForIndianPassport: 'visa-required',
    visaNote: 'UK visa required. Separate from Schengen.',
    visaForEuPassport: 'check-required',
    flightHoursFromEurope: 2,
    highlights: ['Edinburgh Castle', 'Royal Mile', 'Arthur\'s Seat hike'],
  },
  {
    slug: 'florence',
    city: 'Florence', country: 'Italy', region: 'Europe', flag: '🇮🇹', coverEmoji: '🖼️',
    description: 'The birthplace of the Renaissance — Michelangelo, Brunelleschi and Chianti.',
    tags: ['culture', 'history', 'food', 'romance'],
    avgDailyEur: 105, travelStyle: 'mid', bestMonths: [3, 4, 5, 9, 10],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Uffizi Gallery', 'Duomo', 'Ponte Vecchio'],
  },
  {
    slug: 'tbilisi',
    city: 'Tbilisi', country: 'Georgia', region: 'Europe', flag: '🇬🇪', coverEmoji: '🍷',
    description: 'Visa-free for Indians — ancient Silk Road city with incredible wine and food.',
    tags: ['city', 'culture', 'history', 'food', 'adventure'],
    avgDailyEur: 35, travelStyle: 'budget', bestMonths: [4, 5, 6, 9, 10],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians can stay up to 1 year visa-free.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 4,
    highlights: ['Old Town sulfur baths', 'Georgian wine country', 'Kazbegi mountains'],
  },
  {
    slug: 'yerevan',
    city: 'Yerevan', country: 'Armenia', region: 'Europe', flag: '🇦🇲', coverEmoji: '🏔️',
    description: 'Visa-free for Indians — ancient culture, Mount Ararat views and cheap prices.',
    tags: ['city', 'culture', 'history', 'adventure'],
    avgDailyEur: 35, travelStyle: 'budget', bestMonths: [4, 5, 6, 9, 10],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians can stay up to 180 days visa-free.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 4,
    highlights: ['Geghard Monastery', 'Lake Sevan', 'Cascade complex'],
  },
  {
    slug: 'baku',
    city: 'Baku', country: 'Azerbaijan', region: 'Europe', flag: '🇦🇿', coverEmoji: '🔥',
    description: 'Flame towers, medieval old city and oil-boom architecture on the Caspian.',
    tags: ['city', 'culture', 'history'],
    avgDailyEur: 50, travelStyle: 'budget', bestMonths: [4, 5, 9, 10, 11],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Easy e-visa via ASAN system, approved in 3 days.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 5,
    highlights: ['Flame Towers', 'Icherisheher Old City', 'Gobustan petroglyphs'],
  },
  {
    slug: 'warsaw',
    city: 'Warsaw', country: 'Poland', region: 'Europe', flag: '🇵🇱', coverEmoji: '🦅',
    description: 'Rising phoenix — completely rebuilt after WWII, now a thriving modern capital.',
    tags: ['city', 'culture', 'history'],
    avgDailyEur: 55, travelStyle: 'budget', bestMonths: [4, 5, 6, 9, 10],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Old Town (rebuilt)', 'POLIN Museum', 'Chopin concerts'],
  },
  {
    slug: 'valletta',
    city: 'Valletta', country: 'Malta', region: 'Europe', flag: '🇲🇹', coverEmoji: '⚔️',
    description: 'World\'s smallest capital — Knights of Malta history, cliffs and blue lagoons.',
    tags: ['city', 'beach', 'culture', 'history'],
    avgDailyEur: 90, travelStyle: 'mid', bestMonths: [4, 5, 6, 9, 10, 11],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 3,
    highlights: ['Blue Lagoon', 'St John\'s Co-Cathedral', 'Mdina walled city'],
  },
  {
    slug: 'split',
    city: 'Split', country: 'Croatia', region: 'Europe', flag: '🇭🇷', coverEmoji: '🌊',
    description: 'A Roman palace turned living city — gateway to Hvar and Dalmatian islands.',
    tags: ['beach', 'culture', 'history', 'adventure'],
    avgDailyEur: 90, travelStyle: 'mid', bestMonths: [5, 6, 9, 10],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Diocletian\'s Palace', 'Hvar island day trip', 'Plitvice Lakes'],
  },
  {
    slug: 'belgrade',
    city: 'Belgrade', country: 'Serbia', region: 'Europe', flag: '🇷🇸', coverEmoji: '🎵',
    description: 'Europe\'s most underrated party city with fortress, Danube and cheap prices.',
    tags: ['city', 'nightlife', 'culture', 'history'],
    avgDailyEur: 40, travelStyle: 'budget', bestMonths: [4, 5, 6, 9, 10],
    visaForIndianPassport: 'check-required',
    visaNote: 'Indians with valid Schengen or US visa can enter without a Serbian visa.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Kalemegdan Fortress', 'Skadarlija bohemian quarter', 'Floating clubs on Sava'],
  },
  {
    slug: 'zurich',
    city: 'Zurich', country: 'Switzerland', region: 'Europe', flag: '🇨🇭', coverEmoji: '⛰️',
    description: 'Swiss Alps, lake views, chocolate and the world\'s best quality of life.',
    tags: ['city', 'nature', 'culture'],
    avgDailyEur: 220, travelStyle: 'luxury', bestMonths: [4, 5, 6, 7, 8, 9],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 1,
    highlights: ['Lake Zurich', 'Jungfraujoch excursion', 'Old Town'],
  },
  {
    slug: 'copenhagen',
    city: 'Copenhagen', country: 'Denmark', region: 'Europe', flag: '🇩🇰', coverEmoji: '🍦',
    description: 'Noma, hygge, Tivoli Gardens and the happiest people on earth.',
    tags: ['city', 'culture', 'food'],
    avgDailyEur: 150, travelStyle: 'mid', bestMonths: [5, 6, 7, 8],
    visaForIndianPassport: 'schengen', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 2,
    highlights: ['Nyhavn harbour', 'Tivoli Gardens', 'Christiania'],
  },

  // ── ASIA ───────────────────────────────────────────────────────────────────

  {
    slug: 'tokyo',
    city: 'Tokyo', country: 'Japan', region: 'Asia', flag: '🇯🇵', coverEmoji: '⛩️',
    description: 'Neon-lit megacity where ancient temples meet futuristic everything.',
    tags: ['city', 'culture', 'food', 'history'],
    avgDailyEur: 110, travelStyle: 'mid', bestMonths: [3, 4, 10, 11],
    visaForIndianPassport: 'visa-required',
    visaNote: 'Japan tourist visa required for Indians. Apply at Japanese consulate.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 12,
    highlights: ['Shibuya crossing', 'Senso-ji Temple', 'Mt Fuji day trip'],
  },
  {
    slug: 'osaka',
    city: 'Osaka', country: 'Japan', region: 'Asia', flag: '🇯🇵', coverEmoji: '🍜',
    description: 'Japan\'s kitchen — street food capital with incredible nightlife and castles.',
    tags: ['city', 'food', 'culture', 'nightlife'],
    avgDailyEur: 100, travelStyle: 'mid', bestMonths: [3, 4, 10, 11],
    visaForIndianPassport: 'visa-required',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 12,
    highlights: ['Dotonbori food street', 'Osaka Castle', 'Nara deer park day trip'],
  },
  {
    slug: 'bali',
    city: 'Bali', country: 'Indonesia', region: 'Asia', flag: '🇮🇩', coverEmoji: '🌺',
    description: 'Hindu temples, terraced rice fields, surf and spiritual retreats.',
    tags: ['beach', 'nature', 'culture', 'adventure', 'romance'],
    avgDailyEur: 45, travelStyle: 'budget', bestMonths: [4, 5, 6, 7, 8, 9],
    visaForIndianPassport: 'visa-on-arrival',
    visaNote: 'Visa on arrival at Bali airport. $35 USD, valid 30 days.',
    visaForEuPassport: 'visa-on-arrival',
    flightHoursFromEurope: 13,
    highlights: ['Ubud rice terraces', 'Tanah Lot Temple', 'Seminyak beach clubs'],
  },
  {
    slug: 'bangkok',
    city: 'Bangkok', country: 'Thailand', region: 'Asia', flag: '🇹🇭', coverEmoji: '🛺',
    description: 'Temples, street food, rooftop bars and the world\'s craziest city energy.',
    tags: ['city', 'culture', 'food', 'nightlife'],
    avgDailyEur: 40, travelStyle: 'budget', bestMonths: [11, 12, 1, 2, 3],
    visaForIndianPassport: 'visa-on-arrival',
    visaNote: 'Visa on arrival for Indians — 15 days free or apply e-visa for 30 days.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Grand Palace', 'Floating market', 'Khao San Road nightlife'],
  },
  {
    slug: 'chiang-mai',
    city: 'Chiang Mai', country: 'Thailand', region: 'Asia', flag: '🇹🇭', coverEmoji: '🐘',
    description: 'Ancient temple city, elephant sanctuaries and Thailand\'s best street food.',
    tags: ['culture', 'nature', 'adventure', 'food'],
    avgDailyEur: 30, travelStyle: 'budget', bestMonths: [11, 12, 1, 2, 3],
    visaForIndianPassport: 'visa-on-arrival', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 12,
    highlights: ['Doi Suthep temple', 'Elephant Nature Park', 'Sunday Walking Street'],
  },
  {
    slug: 'phuket',
    city: 'Phuket', country: 'Thailand', region: 'Asia', flag: '🇹🇭', coverEmoji: '🏝️',
    description: 'Thailand\'s island paradise — white sand beaches and crystal-clear waters.',
    tags: ['beach', 'nature', 'nightlife'],
    avgDailyEur: 55, travelStyle: 'mid', bestMonths: [11, 12, 1, 2, 3, 4],
    visaForIndianPassport: 'visa-on-arrival', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Phi Phi Islands', 'Phang Nga Bay', 'Patong beach'],
  },
  {
    slug: 'singapore',
    city: 'Singapore', country: 'Singapore', region: 'Asia', flag: '🇸🇬', coverEmoji: '🦁',
    description: 'Ultra-modern city-state — Gardens by the Bay, hawker food and luxury shopping.',
    tags: ['city', 'food', 'culture'],
    avgDailyEur: 120, travelStyle: 'mid', bestMonths: [2, 3, 4, 7, 8],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Apply for Singapore e-visa online before travel.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 13,
    highlights: ['Gardens by the Bay', 'Marina Bay Sands', 'Hawker Centre food'],
  },
  {
    slug: 'kuala-lumpur',
    city: 'Kuala Lumpur', country: 'Malaysia', region: 'Asia', flag: '🇲🇾', coverEmoji: '🏙️',
    description: 'Indians get 30 days FREE — Petronas Towers, jungle within the city, amazing food.',
    tags: ['city', 'food', 'culture'],
    avgDailyEur: 45, travelStyle: 'budget', bestMonths: [3, 4, 5, 6, 7, 8],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians can visit Malaysia visa-free for up to 30 days (2024 policy).',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 13,
    highlights: ['Petronas Twin Towers', 'Batu Caves', 'Jalan Alor food street'],
  },
  {
    slug: 'penang',
    city: 'Penang', country: 'Malaysia', region: 'Asia', flag: '🇲🇾', coverEmoji: '🍛',
    description: 'Malaysia\'s food capital — UNESCO old city, street art and hawker paradise.',
    tags: ['food', 'culture', 'history'],
    avgDailyEur: 35, travelStyle: 'budget', bestMonths: [12, 1, 2, 3, 4],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians can visit Malaysia visa-free for up to 30 days (2024 policy).',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 13,
    highlights: ['George Town street art', 'Kek Lok Si Temple', 'Gurney Drive hawkers'],
  },
  {
    slug: 'maldives',
    city: 'Malé', country: 'Maldives', region: 'Asia', flag: '🇲🇻', coverEmoji: '🐠',
    description: 'Overwater bungalows, turquoise atolls and the world\'s clearest water.',
    tags: ['beach', 'romance', 'nature'],
    avgDailyEur: 220, travelStyle: 'luxury', bestMonths: [11, 12, 1, 2, 3, 4],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians get 30-day free on-arrival visa.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 9,
    highlights: ['Overwater bungalows', 'Snorkelling with manta rays', 'Bioluminescent beach'],
  },
  {
    slug: 'sri-lanka',
    city: 'Colombo', country: 'Sri Lanka', region: 'Asia', flag: '🇱🇰', coverEmoji: '🫖',
    description: 'Temple of the Tooth, tea plantations, wildlife and a stunning coastline.',
    tags: ['culture', 'nature', 'beach', 'history'],
    avgDailyEur: 38, travelStyle: 'budget', bestMonths: [12, 1, 2, 3, 4],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Simple ETA (electronic travel authority) online, approved quickly.',
    visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 9,
    highlights: ['Sigiriya Rock', 'Kandy Temple of the Tooth', 'Yala Safari'],
  },
  {
    slug: 'kathmandu',
    city: 'Kathmandu', country: 'Nepal', region: 'Asia', flag: '🇳🇵', coverEmoji: '🏔️',
    description: 'Gateway to the Himalayas — Indians enter with just their ID card, no passport.',
    tags: ['culture', 'nature', 'adventure', 'history'],
    avgDailyEur: 25, travelStyle: 'budget', bestMonths: [3, 4, 10, 11],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians can enter Nepal without a passport — just an Indian ID card.',
    visaForEuPassport: 'visa-on-arrival',
    flightHoursFromEurope: 8,
    highlights: ['Everest Base Camp trek', 'Pashupatinath Temple', 'Boudhanath Stupa'],
  },
  {
    slug: 'pokhara',
    city: 'Pokhara', country: 'Nepal', region: 'Asia', flag: '🇳🇵', coverEmoji: '🪂',
    description: 'Paragliding over Phewa Lake with Annapurna views — budget paradise for Indians.',
    tags: ['nature', 'adventure'],
    avgDailyEur: 22, travelStyle: 'budget', bestMonths: [3, 4, 10, 11],
    visaForIndianPassport: 'visa-free', visaForEuPassport: 'visa-on-arrival',
    flightHoursFromEurope: 9,
    highlights: ['Paragliding over Phewa Lake', 'Annapurna Circuit', 'World Peace Pagoda'],
  },
  {
    slug: 'bhutan',
    city: 'Thimphu', country: 'Bhutan', region: 'Asia', flag: '🇧🇹', coverEmoji: '🐉',
    description: 'The last Himalayan kingdom — happiness over GDP, Tiger\'s Nest monastery.',
    tags: ['culture', 'nature', 'adventure'],
    avgDailyEur: 90, travelStyle: 'mid', bestMonths: [3, 4, 5, 10, 11],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians enter Bhutan visa-free with Indian passport or voter ID.',
    visaForEuPassport: 'visa-required',
    flightHoursFromEurope: 10,
    highlights: ['Tiger\'s Nest monastery', 'Punakha Dzong', 'Dochula Pass'],
  },
  {
    slug: 'hanoi',
    city: 'Hanoi', country: 'Vietnam', region: 'Asia', flag: '🇻🇳', coverEmoji: '🍲',
    description: 'French-colonial streets, egg coffee, Hoan Kiem Lake and Halong Bay nearby.',
    tags: ['city', 'culture', 'food', 'history'],
    avgDailyEur: 30, travelStyle: 'budget', bestMonths: [10, 11, 12, 3, 4],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Vietnam e-visa available online, 90 days single entry.',
    visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 10,
    highlights: ['Ha Long Bay cruise', 'Old Quarter street food', 'Ho Chi Minh Mausoleum'],
  },
  {
    slug: 'ho-chi-minh',
    city: 'Ho Chi Minh City', country: 'Vietnam', region: 'Asia', flag: '🇻🇳', coverEmoji: '🛵',
    description: 'Saigon\'s electric energy — War Museum, Cu Chi Tunnels, street food chaos.',
    tags: ['city', 'culture', 'food', 'history'],
    avgDailyEur: 35, travelStyle: 'budget', bestMonths: [12, 1, 2, 3, 4],
    visaForIndianPassport: 'e-visa', visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 11,
    highlights: ['Cu Chi Tunnels', 'War Remnants Museum', 'Ben Thanh Market'],
  },
  {
    slug: 'da-nang',
    city: 'Da Nang', country: 'Vietnam', region: 'Asia', flag: '🇻🇳', coverEmoji: '🌉',
    description: 'Between Hoi An\'s lanterns and Hue\'s imperial city — perfect beach base.',
    tags: ['beach', 'culture', 'nature'],
    avgDailyEur: 32, travelStyle: 'budget', bestMonths: [2, 3, 4, 5, 8, 9],
    visaForIndianPassport: 'e-visa', visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 11,
    highlights: ['Hoi An Ancient Town', 'My Son Sanctuary', 'My Khe Beach'],
  },
  {
    slug: 'siem-reap',
    city: 'Siem Reap', country: 'Cambodia', region: 'Asia', flag: '🇰🇭', coverEmoji: '🛕',
    description: 'Angkor Wat — the world\'s largest temple complex, sunrise over stone giants.',
    tags: ['culture', 'history', 'adventure'],
    avgDailyEur: 35, travelStyle: 'budget', bestMonths: [11, 12, 1, 2, 3],
    visaForIndianPassport: 'visa-on-arrival',
    visaNote: 'Visa on arrival at Siem Reap airport. $30 USD.',
    visaForEuPassport: 'visa-on-arrival',
    flightHoursFromEurope: 13,
    highlights: ['Angkor Wat sunrise', 'Bayon Temple', 'Tonle Sap floating villages'],
  },
  {
    slug: 'luang-prabang',
    city: 'Luang Prabang', country: 'Laos', region: 'Asia', flag: '🇱🇦', coverEmoji: '🌅',
    description: 'Monk alms giving at dawn, Mekong sunsets and waterfalls in the jungle.',
    tags: ['culture', 'nature', 'history'],
    avgDailyEur: 30, travelStyle: 'budget', bestMonths: [11, 12, 1, 2, 3],
    visaForIndianPassport: 'visa-on-arrival', visaForEuPassport: 'visa-on-arrival',
    flightHoursFromEurope: 13,
    highlights: ['Alms giving ceremony', 'Kuang Si waterfalls', 'Mekong sunset cruise'],
  },
  {
    slug: 'istanbul',
    city: 'Istanbul', country: 'Turkey', region: 'Asia', flag: '🇹🇷', coverEmoji: '🕌',
    description: 'Where East meets West — Blue Mosque, Grand Bazaar and the Bosphorus.',
    tags: ['city', 'culture', 'food', 'history'],
    avgDailyEur: 55, travelStyle: 'mid', bestMonths: [4, 5, 9, 10, 11],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Turkish e-visa easily available online, $51, processed in minutes.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 3,
    highlights: ['Hagia Sophia', 'Grand Bazaar', 'Bosphorus boat cruise'],
  },
  {
    slug: 'amman',
    city: 'Amman', country: 'Jordan', region: 'Asia', flag: '🇯🇴', coverEmoji: '🏜️',
    description: 'Petra, Wadi Rum, Dead Sea and the most welcoming people in the Middle East.',
    tags: ['culture', 'history', 'adventure', 'nature'],
    avgDailyEur: 65, travelStyle: 'mid', bestMonths: [3, 4, 10, 11],
    visaForIndianPassport: 'visa-on-arrival',
    visaNote: 'Visa on arrival available for Indians.',
    visaForEuPassport: 'visa-on-arrival',
    flightHoursFromEurope: 4,
    highlights: ['Petra (rose-red city)', 'Wadi Rum desert camp', 'Dead Sea float'],
  },
  {
    slug: 'doha',
    city: 'Doha', country: 'Qatar', region: 'Asia', flag: '🇶🇦', coverEmoji: '🏙️',
    description: 'Indians get FREE visa on arrival — luxury skyline, souqs and desert safaris.',
    tags: ['city', 'culture', 'food'],
    avgDailyEur: 80, travelStyle: 'mid', bestMonths: [11, 12, 1, 2, 3],
    visaForIndianPassport: 'visa-on-arrival',
    visaNote: 'Indians get free 30-day visa on arrival in Qatar.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 6,
    highlights: ['Museum of Islamic Art', 'Souq Waqif', 'Desert safari'],
  },
  {
    slug: 'muscat',
    city: 'Muscat', country: 'Oman', region: 'Asia', flag: '🇴🇲', coverEmoji: '🏰',
    description: 'The Gulf\'s safest, cleanest destination — wadis, forts and the Grand Mosque.',
    tags: ['culture', 'nature', 'adventure', 'history'],
    avgDailyEur: 70, travelStyle: 'mid', bestMonths: [11, 12, 1, 2, 3],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Oman e-visa for Indians available online.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 7,
    highlights: ['Sultan Qaboos Grand Mosque', 'Wadi Shab', 'Nizwa Fort'],
  },
  {
    slug: 'dubai',
    city: 'Dubai', country: 'UAE', region: 'Asia', flag: '🇦🇪', coverEmoji: '🏗️',
    description: 'Burj Khalifa, desert safaris and the most extravagant city on the planet.',
    tags: ['city', 'nightlife', 'food'],
    avgDailyEur: 130, travelStyle: 'luxury', bestMonths: [11, 12, 1, 2, 3],
    visaForIndianPassport: 'visa-required',
    visaNote: 'UAE visa required for Indians. However, if you hold a valid US or UK visa, you get free 14-day visa on arrival.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 7,
    highlights: ['Burj Khalifa', 'Desert safari', 'Dubai Mall & Souk'],
  },
  {
    slug: 'riyadh',
    city: 'Riyadh', country: 'Saudi Arabia', region: 'Asia', flag: '🇸🇦', coverEmoji: '🕌',
    description: 'Saudi Arabia opened to tourists — AlUla ruins, Edge of the World, futurism.',
    tags: ['culture', 'history', 'adventure'],
    avgDailyEur: 80, travelStyle: 'mid', bestMonths: [11, 12, 1, 2, 3],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Saudi tourist e-visa now available for Indians online.',
    visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 6,
    highlights: ['AlUla ancient ruins', 'Edge of the World cliff', 'Diriyah old city'],
  },
  {
    slug: 'almaty',
    city: 'Almaty', country: 'Kazakhstan', region: 'Asia', flag: '🇰🇿', coverEmoji: '🏔️',
    description: 'Soviet-era charm meets Tian Shan mountains — apple orchards and adventure.',
    tags: ['nature', 'adventure', 'culture'],
    avgDailyEur: 45, travelStyle: 'budget', bestMonths: [5, 6, 7, 8, 9],
    visaForIndianPassport: 'e-visa', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 7,
    highlights: ['Big Almaty Lake', 'Medeu ice rink', 'Charyn Canyon'],
  },
  {
    slug: 'tashkent',
    city: 'Tashkent', country: 'Uzbekistan', region: 'Asia', flag: '🇺🇿', coverEmoji: '🕌',
    description: 'Samarkand, Bukhara, Silk Road — the most underrated trip in Central Asia.',
    tags: ['culture', 'history', 'adventure'],
    avgDailyEur: 35, travelStyle: 'budget', bestMonths: [3, 4, 5, 9, 10],
    visaForIndianPassport: 'e-visa', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 7,
    highlights: ['Samarkand Registan', 'Bukhara old city', 'Khiva walled city'],
  },
  {
    slug: 'bishkek',
    city: 'Bishkek', country: 'Kyrgyzstan', region: 'Asia', flag: '🇰🇬', coverEmoji: '🏕️',
    description: 'Nomadic yurt camps, mountain lakes and the most untouched scenery in Asia.',
    tags: ['nature', 'adventure'],
    avgDailyEur: 28, travelStyle: 'budget', bestMonths: [5, 6, 7, 8, 9],
    visaForIndianPassport: 'visa-on-arrival', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 8,
    highlights: ['Issyk-Kul Lake', 'Song-Kol yurt camp', 'Ala Archa gorge hike'],
  },
  {
    slug: 'seoul',
    city: 'Seoul', country: 'South Korea', region: 'Asia', flag: '🇰🇷', coverEmoji: '🎎',
    description: 'K-pop, palaces, BBQ, skincare and the most wired city in the world.',
    tags: ['city', 'culture', 'food', 'nightlife'],
    avgDailyEur: 90, travelStyle: 'mid', bestMonths: [3, 4, 5, 9, 10, 11],
    visaForIndianPassport: 'visa-required',
    visaNote: 'Visa required for Indians. Apply at Korean consulate.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Gyeongbokgung Palace', 'DMZ tour', 'Gangnam & Myeongdong'],
  },
  {
    slug: 'taipei',
    city: 'Taipei', country: 'Taiwan', region: 'Asia', flag: '🇹🇼', coverEmoji: '🏮',
    description: 'Night markets, bubble tea, Taipei 101 and the warmest people in Asia.',
    tags: ['city', 'food', 'culture'],
    avgDailyEur: 65, travelStyle: 'mid', bestMonths: [3, 4, 10, 11],
    visaForIndianPassport: 'check-required',
    visaNote: 'Indians holding valid US visa may qualify for visa-free entry. Otherwise, apply for Taiwan visa.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 13,
    highlights: ['Taipei 101', 'Jiufen old town', 'Shilin Night Market'],
  },

  // ── MIDDLE EAST ────────────────────────────────────────────────────────────

  {
    slug: 'bahrain',
    city: 'Manama', country: 'Bahrain', region: 'Middle East', flag: '🇧🇭', coverEmoji: '🌴',
    description: 'Tiny island kingdom — F1 circuit, ancient burial mounds and pearl diving heritage.',
    tags: ['culture', 'history', 'city'],
    avgDailyEur: 70, travelStyle: 'mid', bestMonths: [11, 12, 1, 2, 3],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Bahrain e-visa available for Indians online.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 6,
    highlights: ['Al Fateh Mosque', 'Bahrain Fort', 'Formula 1 circuit'],
  },

  // ── AFRICA ─────────────────────────────────────────────────────────────────

  {
    slug: 'mauritius',
    city: 'Port Louis', country: 'Mauritius', region: 'Africa', flag: '🇲🇺', coverEmoji: '🏝️',
    description: 'Indians enter VISA FREE — underwater waterfall, turquoise lagoons, pure luxury.',
    tags: ['beach', 'romance', 'nature'],
    avgDailyEur: 120, travelStyle: 'luxury', bestMonths: [5, 6, 7, 8, 9, 10],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians can stay up to 90 days visa-free.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Le Morne beach', 'Black River Gorges hike', 'Underwater waterfall illusion'],
  },
  {
    slug: 'seychelles',
    city: 'Mahé', country: 'Seychelles', region: 'Africa', flag: '🇸🇨', coverEmoji: '🦜',
    description: 'Indians enter VISA FREE — granite boulders, paradise beaches, no mass tourism.',
    tags: ['beach', 'romance', 'nature'],
    avgDailyEur: 180, travelStyle: 'luxury', bestMonths: [4, 5, 10, 11],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Visitor\'s permit issued on arrival, free of charge for Indians.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Anse Lazio beach', 'Vallée de Mai (Coco de Mer)', 'Island hopping'],
  },
  {
    slug: 'marrakech',
    city: 'Marrakech', country: 'Morocco', region: 'Africa', flag: '🇲🇦', coverEmoji: '🕌',
    description: 'Souqs, snake charmers, riads and the Atlas Mountains at your doorstep.',
    tags: ['culture', 'history', 'adventure', 'food'],
    avgDailyEur: 50, travelStyle: 'budget', bestMonths: [3, 4, 10, 11],
    visaForIndianPassport: 'visa-required',
    visaNote: 'Visa required for Indians. Apply at Moroccan consulate.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 3,
    highlights: ['Jemaa el-Fnaa square', 'Bahia Palace', 'Sahara desert excursion'],
  },
  {
    slug: 'cairo',
    city: 'Cairo', country: 'Egypt', region: 'Africa', flag: '🇪🇬', coverEmoji: '🐪',
    description: 'Pyramids of Giza, Nile cruises, Sphinx and the greatest open-air museum.',
    tags: ['culture', 'history', 'adventure'],
    avgDailyEur: 40, travelStyle: 'budget', bestMonths: [10, 11, 12, 1, 2, 3],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Egypt e-visa easily available online for Indians.',
    visaForEuPassport: 'visa-on-arrival',
    flightHoursFromEurope: 4,
    highlights: ['Pyramids of Giza', 'Egyptian Museum', 'Nile felucca sail'],
  },
  {
    slug: 'cape-town',
    city: 'Cape Town', country: 'South Africa', region: 'Africa', flag: '🇿🇦', coverEmoji: '🦁',
    description: 'Table Mountain, wine country, penguin beaches and the Garden Route.',
    tags: ['nature', 'adventure', 'city', 'beach'],
    avgDailyEur: 60, travelStyle: 'mid', bestMonths: [10, 11, 12, 1, 2, 3],
    visaForIndianPassport: 'visa-required',
    visaNote: 'Visa required for Indians. Apply at South African High Commission.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Table Mountain cable car', 'Cape of Good Hope', 'Boulders penguin colony'],
  },
  {
    slug: 'nairobi',
    city: 'Nairobi', country: 'Kenya', region: 'Africa', flag: '🇰🇪', coverEmoji: '🦒',
    description: 'Safari capital of the world — Maasai Mara and lion sunsets on the savannah.',
    tags: ['nature', 'adventure', 'culture'],
    avgDailyEur: 65, travelStyle: 'mid', bestMonths: [7, 8, 1, 2, 9, 10],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Kenya e-visa available online for Indians.',
    visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 8,
    highlights: ['Maasai Mara Great Migration', 'Amboseli (Kilimanjaro views)', 'Nairobi National Park'],
  },
  {
    slug: 'zanzibar',
    city: 'Zanzibar', country: 'Tanzania', region: 'Africa', flag: '🇹🇿', coverEmoji: '🏖️',
    description: 'Spice island paradise — turquoise water, Stone Town UNESCO and powder-white sand.',
    tags: ['beach', 'culture', 'history'],
    avgDailyEur: 55, travelStyle: 'mid', bestMonths: [6, 7, 8, 9, 12, 1, 2],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Tanzania e-visa available for Indians online.',
    visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 9,
    highlights: ['Nungwi beach', 'Stone Town UNESCO', 'Spice plantation tour'],
  },
  {
    slug: 'kigali',
    city: 'Kigali', country: 'Rwanda', region: 'Africa', flag: '🇷🇼', coverEmoji: '🦍',
    description: 'Africa\'s cleanest city — gorilla trekking, genocide memorial, remarkable recovery.',
    tags: ['nature', 'adventure', 'culture'],
    avgDailyEur: 55, travelStyle: 'mid', bestMonths: [6, 7, 8, 12, 1, 2],
    visaForIndianPassport: 'visa-on-arrival',
    visaNote: 'Indians get visa on arrival in Rwanda.',
    visaForEuPassport: 'visa-on-arrival',
    flightHoursFromEurope: 8,
    highlights: ['Gorilla trekking (Volcanoes NP)', 'Genocide Memorial', 'Nyungwe forest'],
  },
  {
    slug: 'addis-ababa',
    city: 'Addis Ababa', country: 'Ethiopia', region: 'Africa', flag: '🇪🇹', coverEmoji: '☕',
    description: 'Birthplace of coffee, ancient churches, Lalibela rock-hewn monasteries.',
    tags: ['culture', 'history', 'adventure'],
    avgDailyEur: 35, travelStyle: 'budget', bestMonths: [10, 11, 12, 1, 2, 3],
    visaForIndianPassport: 'visa-on-arrival',
    visaNote: 'Ethiopia offers visa on arrival for Indians.',
    visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 8,
    highlights: ['Lalibela rock churches', 'Danakil Depression', 'Simien Mountains trek'],
  },
  {
    slug: 'accra',
    city: 'Accra', country: 'Ghana', region: 'Africa', flag: '🇬🇭', coverEmoji: '🥁',
    description: 'West Africa\'s most vibrant city — Afrobeats, slave castles and Afrobeach.',
    tags: ['city', 'culture', 'history'],
    avgDailyEur: 50, travelStyle: 'mid', bestMonths: [11, 12, 1, 2],
    visaForIndianPassport: 'e-visa',
    visaNote: 'Ghana e-visa available for Indians.',
    visaForEuPassport: 'visa-required',
    flightHoursFromEurope: 6,
    highlights: ['Cape Coast Castle', 'Kakum National Park canopy walk', 'Labadi Beach'],
  },
  {
    slug: 'victoria-falls',
    city: 'Livingstone', country: 'Zambia / Zimbabwe', region: 'Africa', flag: '🇿🇲', coverEmoji: '🌊',
    description: 'The world\'s largest waterfall — bungee jump over the Zambezi, Devil\'s Pool.',
    tags: ['nature', 'adventure'],
    avgDailyEur: 70, travelStyle: 'mid', bestMonths: [3, 4, 5, 7, 8, 9],
    visaForIndianPassport: 'visa-on-arrival',
    visaNote: 'KAZA Univisa ($50) covers Zambia + Zimbabwe — available on arrival.',
    visaForEuPassport: 'visa-on-arrival',
    flightHoursFromEurope: 11,
    highlights: ['Victoria Falls (Mosi-oa-Tunya)', 'Devil\'s Pool', 'Sunset cruise on Zambezi'],
  },

  // ── AMERICAS ──────────────────────────────────────────────────────────────

  {
    slug: 'new-york',
    city: 'New York', country: 'USA', region: 'Americas', flag: '🇺🇸', coverEmoji: '🗽',
    description: 'The city that never sleeps — Times Square, Central Park, pizza and bagels.',
    tags: ['city', 'culture', 'food', 'nightlife'],
    avgDailyEur: 200, travelStyle: 'mid', bestMonths: [4, 5, 6, 9, 10],
    visaForIndianPassport: 'visa-required',
    visaNote: 'US B-1/B-2 tourist visa required. Apply well in advance.',
    visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 8,
    highlights: ['Central Park', 'Statue of Liberty', 'Brooklyn & Manhattan skyline'],
  },
  {
    slug: 'miami',
    city: 'Miami', country: 'USA', region: 'Americas', flag: '🇺🇸', coverEmoji: '🌴',
    description: 'Art Deco beaches, Cuban food, Wynwood murals and year-round sunshine.',
    tags: ['beach', 'city', 'nightlife', 'food'],
    avgDailyEur: 180, travelStyle: 'mid', bestMonths: [11, 12, 1, 2, 3, 4],
    visaForIndianPassport: 'visa-required', visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 10,
    highlights: ['South Beach', 'Art Basel / Wynwood', 'Everglades day trip'],
  },
  {
    slug: 'cancun',
    city: 'Cancún', country: 'Mexico', region: 'Americas', flag: '🇲🇽', coverEmoji: '🌮',
    description: 'Caribbean coast, Mayan ruins at Tulum and Chichen Itza — plus cenotes.',
    tags: ['beach', 'culture', 'history', 'adventure'],
    avgDailyEur: 70, travelStyle: 'mid', bestMonths: [11, 12, 1, 2, 3, 4],
    visaForIndianPassport: 'check-required',
    visaNote: 'Indians with valid US visa can enter Mexico without a visa. Otherwise, apply for Mexican visa.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Tulum ruins', 'Chichen Itza', 'Cenote swimming'],
  },
  {
    slug: 'mexico-city',
    city: 'Mexico City', country: 'Mexico', region: 'Americas', flag: '🇲🇽', coverEmoji: '🏟️',
    description: 'Aztec pyramids, world-class museums, street tacos and a wild art scene.',
    tags: ['city', 'culture', 'history', 'food'],
    avgDailyEur: 55, travelStyle: 'budget', bestMonths: [3, 4, 10, 11, 12],
    visaForIndianPassport: 'check-required',
    visaNote: 'Indians with valid US visa can enter visa-free. Otherwise, Mexican visa required.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Teotihuacan pyramids', 'Frida Kahlo Museum', 'Zócalo & Bellas Artes'],
  },
  {
    slug: 'bogota',
    city: 'Bogotá', country: 'Colombia', region: 'Americas', flag: '🇨🇴', coverEmoji: '💎',
    description: 'Indians enter VISA FREE — street art, Gold Museum, coffee region day trips.',
    tags: ['city', 'culture', 'history', 'adventure'],
    avgDailyEur: 45, travelStyle: 'budget', bestMonths: [12, 1, 2, 6, 7, 8],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians can enter Colombia visa-free for up to 90 days.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Gold Museum', 'Monserrate hill', 'Salento coffee region'],
  },
  {
    slug: 'medellin',
    city: 'Medellín', country: 'Colombia', region: 'Americas', flag: '🇨🇴', coverEmoji: '🌸',
    description: 'City of eternal spring — cable cars, flower festivals and amazing innovation.',
    tags: ['city', 'culture', 'nature'],
    avgDailyEur: 40, travelStyle: 'budget', bestMonths: [12, 1, 2, 6, 7, 8],
    visaForIndianPassport: 'visa-free', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Metro cable car views', 'Parque Arví', 'Pablo Escobar tour'],
  },
  {
    slug: 'cartagena',
    city: 'Cartagena', country: 'Colombia', region: 'Americas', flag: '🇨🇴', coverEmoji: '🏰',
    description: 'Colourful colonial walled city on the Caribbean — magical for a couple.',
    tags: ['city', 'beach', 'history', 'romance'],
    avgDailyEur: 55, travelStyle: 'mid', bestMonths: [12, 1, 2, 3],
    visaForIndianPassport: 'visa-free', visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Walled city & castles', 'Rosario Islands', 'Getsemaní street art'],
  },
  {
    slug: 'buenos-aires',
    city: 'Buenos Aires', country: 'Argentina', region: 'Americas', flag: '🇦🇷', coverEmoji: '💃',
    description: 'Tango, steak, Malbec and the Paris of South America.',
    tags: ['city', 'culture', 'food', 'nightlife'],
    avgDailyEur: 45, travelStyle: 'mid', bestMonths: [9, 10, 11, 3, 4],
    visaForIndianPassport: 'check-required',
    visaNote: 'Argentina recently changed visa policies. Indians should check current requirements before travel.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 14,
    highlights: ['La Boca Caminito', 'Tango show in San Telmo', 'Recoleta Cemetery'],
  },
  {
    slug: 'lima',
    city: 'Lima', country: 'Peru', region: 'Americas', flag: '🇵🇪', coverEmoji: '🏔️',
    description: 'World\'s best restaurant city — gateway to Machu Picchu and the Amazon.',
    tags: ['city', 'culture', 'food', 'adventure'],
    avgDailyEur: 50, travelStyle: 'mid', bestMonths: [12, 1, 2, 3, 4],
    visaForIndianPassport: 'check-required',
    visaNote: 'Verify current visa requirements for Indians before travel.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 12,
    highlights: ['Machu Picchu', 'Amazon jungle lodge', 'Miraflores cliff walk'],
  },
  {
    slug: 'jamaicakingston',
    city: 'Kingston', country: 'Jamaica', region: 'Americas', flag: '🇯🇲', coverEmoji: '🎵',
    description: 'Indians enter VISA FREE — Bob Marley, reggae, Blue Mountains and Dunn\'s River.',
    tags: ['beach', 'culture', 'nature'],
    avgDailyEur: 70, travelStyle: 'mid', bestMonths: [12, 1, 2, 3, 4, 5],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians can visit Jamaica visa-free.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 10,
    highlights: ['Bob Marley Museum', 'Dunn\'s River Falls', 'Blue Mountains coffee'],
  },
  {
    slug: 'trinidad',
    city: 'Port of Spain', country: 'Trinidad & Tobago', region: 'Americas', flag: '🇹🇹', coverEmoji: '🦜',
    description: 'Indians enter VISA FREE — Carnival, steel pan, rum and rainforest wildlife.',
    tags: ['culture', 'nature', 'beach'],
    avgDailyEur: 70, travelStyle: 'mid', bestMonths: [1, 2, 3, 1, 2],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians can visit Trinidad & Tobago visa-free.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 10,
    highlights: ['Carnival (Feb)', 'Asa Wright Nature Centre', 'Pigeon Point beach (Tobago)'],
  },
  {
    slug: 'toronto',
    city: 'Toronto', country: 'Canada', region: 'Americas', flag: '🇨🇦', coverEmoji: '🍁',
    description: 'Canada\'s most cosmopolitan city — Niagara Falls nearby and incredible food.',
    tags: ['city', 'culture', 'food'],
    avgDailyEur: 150, travelStyle: 'mid', bestMonths: [5, 6, 7, 8, 9],
    visaForIndianPassport: 'visa-required',
    visaNote: 'Canadian tourist visa required for Indians.',
    visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 8,
    highlights: ['CN Tower', 'Niagara Falls', 'Kensington Market'],
  },
  {
    slug: 'panama-city',
    city: 'Panama City', country: 'Panama', region: 'Americas', flag: '🇵🇦', coverEmoji: '⚓',
    description: 'The canal, a stunning old city and the gateway between two oceans.',
    tags: ['city', 'culture', 'history'],
    avgDailyEur: 65, travelStyle: 'mid', bestMonths: [12, 1, 2, 3],
    visaForIndianPassport: 'check-required',
    visaNote: 'Indians should verify current Panama visa requirements before travel.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Panama Canal locks', 'Casco Viejo old town', 'San Blas islands'],
  },
  {
    slug: 'san-jose-cr',
    city: 'San José', country: 'Costa Rica', region: 'Americas', flag: '🇨🇷', coverEmoji: '🐸',
    description: 'Pura Vida — cloud forests, volcanoes, sloths and the world\'s best biodiversity.',
    tags: ['nature', 'adventure', 'family'],
    avgDailyEur: 70, travelStyle: 'mid', bestMonths: [12, 1, 2, 3, 4],
    visaForIndianPassport: 'check-required',
    visaNote: 'Verify current Costa Rica visa requirements for Indians.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 11,
    highlights: ['Arenal Volcano', 'Monteverde Cloud Forest', 'Manuel Antonio beach wildlife'],
  },

  // ── OCEANIA ────────────────────────────────────────────────────────────────

  {
    slug: 'sydney',
    city: 'Sydney', country: 'Australia', region: 'Oceania', flag: '🇦🇺', coverEmoji: '🦘',
    description: 'Opera House, Bondi Beach, the Harbour Bridge and incredible coastal walks.',
    tags: ['city', 'beach', 'nature', 'culture'],
    avgDailyEur: 155, travelStyle: 'mid', bestMonths: [9, 10, 11, 12, 3, 4],
    visaForIndianPassport: 'visa-required',
    visaNote: 'Australian tourist visa (ETA or eVisitor) required for Indians. Apply online.',
    visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 22,
    highlights: ['Sydney Opera House', 'Bondi Beach', 'Blue Mountains'],
  },
  {
    slug: 'melbourne',
    city: 'Melbourne', country: 'Australia', region: 'Oceania', flag: '🇦🇺', coverEmoji: '☕',
    description: 'Australia\'s coffee and culture capital — laneways, street art, sports.',
    tags: ['city', 'culture', 'food'],
    avgDailyEur: 145, travelStyle: 'mid', bestMonths: [9, 10, 11, 3, 4],
    visaForIndianPassport: 'visa-required', visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 22,
    highlights: ['Great Ocean Road', 'Queen Victoria Market', 'Penguin parade Phillip Island'],
  },
  {
    slug: 'auckland',
    city: 'Auckland', country: 'New Zealand', region: 'Oceania', flag: '🇳🇿', coverEmoji: '🌿',
    description: 'Hobbiton, Milford Sound, Rotorua geysers — Middle-earth in real life.',
    tags: ['nature', 'adventure', 'culture'],
    avgDailyEur: 140, travelStyle: 'mid', bestMonths: [11, 12, 1, 2, 3],
    visaForIndianPassport: 'visa-required',
    visaNote: 'NZeTA (electronic travel authority) required for Indians — apply online.',
    visaForEuPassport: 'visa-required',
    flightHoursFromEurope: 24,
    highlights: ['Hobbiton movie set', 'Milford Sound', 'Rotorua geothermal'],
  },
  {
    slug: 'queenstown',
    city: 'Queenstown', country: 'New Zealand', region: 'Oceania', flag: '🇳🇿', coverEmoji: '🪂',
    description: 'Adventure capital of the world — bungee, skydiving and Fiordland.',
    tags: ['adventure', 'nature'],
    avgDailyEur: 145, travelStyle: 'mid', bestMonths: [11, 12, 1, 2, 3],
    visaForIndianPassport: 'visa-required', visaForEuPassport: 'visa-required',
    flightHoursFromEurope: 24,
    highlights: ['Bungee jumping', 'Fiordland / Milford Sound', 'The Remarkables ski field'],
  },
  {
    slug: 'fiji',
    city: 'Nadi', country: 'Fiji', region: 'Oceania', flag: '🇫🇯', coverEmoji: '🐚',
    description: 'Indians enter VISA FREE — 300 islands, coral reefs and the friendliest people.',
    tags: ['beach', 'romance', 'nature', 'family'],
    avgDailyEur: 90, travelStyle: 'mid', bestMonths: [5, 6, 7, 8, 9, 10],
    visaForIndianPassport: 'visa-free',
    visaNote: 'Indians can visit Fiji visa-free for up to 4 months.',
    visaForEuPassport: 'visa-free',
    flightHoursFromEurope: 20,
    highlights: ['Yasawa Islands snorkelling', 'Coral Coast resorts', 'Sabeto hot springs'],
  },
  {
    slug: 'gold-coast',
    city: 'Gold Coast', country: 'Australia', region: 'Oceania', flag: '🇦🇺', coverEmoji: '🏄',
    description: 'Theme parks, surf beaches, hinterland rainforest — Australia\'s fun coast.',
    tags: ['beach', 'adventure', 'family'],
    avgDailyEur: 130, travelStyle: 'mid', bestMonths: [5, 6, 7, 8, 9, 10],
    visaForIndianPassport: 'visa-required', visaForEuPassport: 'e-visa',
    flightHoursFromEurope: 22,
    highlights: ['Surfers Paradise beach', 'Movie World theme park', 'Lamington National Park'],
  },
]

export function getDestinationBySlug(slug: string): Destination | undefined {
  return DESTINATIONS.find(d => d.slug === slug)
}

export function getDestinationsByRegion(region: Region): Destination[] {
  return DESTINATIONS.filter(d => d.region === region)
}
